---
# playbooks/main.yml
- name: Set up Intel User Lab Infrastructure
  hosts: all
  become: true
  roles:
    - static_ip_config
    - user_setup
    - dhcp
    - dns
    - ntp
    - firewall
    - network_config
    - hosts_updater

